media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: blog
    fields:
      - name: title
        type: string
      - name: image
        label: Featured Thumbnail
        type: image
      - name: sections
        label: Article Sections
        type: list
        fields:
          - name: subtitle
            label: Subtitle / Heading
            type: string
          - name: section_image
            label: Section Image
            type: image
          - name: content
            label: Article Details
            type: rich-text
