media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: blog
    fields:
      - name: title
        type: string
      - name: image
        label: Featured Image (Thumbnail)
        type: image
      - name: body
        type: rich-text
