// Shared across all pages: mobile nav, FAQ accordion, contact form, toast messages
function toggleMobileMenu() {
  document.getElementById('mobileNav').classList.toggle('active');
}

function toggleFaq(element) {
  const faqItem = element.parentElement;
  const isActive = faqItem.classList.contains('active');
  document.querySelectorAll('.faq-item').forEach(item => { item.classList.remove('active'); });
  if (!isActive) { faqItem.classList.add('active'); }
}

function handleContactSubmit(e) {
  e.preventDefault();
  showToast('Thank you! Your message has been sent.');
  e.target.reset();
}

// Builds the HTML for one blog card - shared by renderRelatedArticles and
// renderAllArticles so both use the exact same card markup/format.
function buildBlogCardHtml(a) {
  const dateDisplay = new Date(a.date + 'T00:00:00').toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `
  <!-- Blog Card - ${a.title} -->
  <div class="blog-card">
      <div class="blog-thumbnail">
          <img src="${a.image}" alt="${a.imageAlt || a.title}">
      </div>
      <div class="blog-card-content">
          <div class="blog-category">${a.category || 'PET CARE'}</div>
          <h3>
              <a href="${a.url}">
                  ${a.title}
              </a>
          </h3>
          <p>
              ${a.excerpt}
          </p>
          <div class="blog-meta">📅 ${dateDisplay} &nbsp;|&nbsp; ⏱️ ${a.readTime || '5 min read'}</div>
      </div>
  </div>
  `;
}

// Renders 4 "related article" cards at the bottom of a blog article, pulled
// automatically from /blog/articles.json (auto-generated by GitHub Actions
// every time a new .html file is pushed into the /blog/ folder).
async function renderRelatedArticles(containerId, count) {
  count = count || 4;
  const container = document.getElementById(containerId);
  if (!container) return;
  try {
    const res = await fetch('/blog/articles.json');
    if (!res.ok) throw new Error('articles.json not found');
    const articles = await res.json();
    const currentUrl = window.location.pathname;
    const others = articles
      .filter(a => a.url !== currentUrl)
      .sort((a, b) => new Date(b.date) - new Date(a.date))
      .slice(0, count);

    if (others.length === 0) {
      const section = container.closest('.related-articles-section');
      if (section) section.style.display = 'none';
      return;
    }

    container.innerHTML = others.map(buildBlogCardHtml).join('');
  } catch (err) {
    console.error('Could not load related articles:', err);
    const section = container.closest('.related-articles-section');
    if (section) section.style.display = 'none';
  }
}

// Renders EVERY blog article as a card - used on blog/index.html so the
// blog listing page always shows every article automatically, newest first.
// Nothing to paste manually - GitHub Actions keeps articles.json up to date.
async function renderAllArticles(containerId, emptyMessage) {
  const container = document.getElementById(containerId);
  if (!container) return;
  try {
    const res = await fetch('/blog/articles.json');
    if (!res.ok) throw new Error('articles.json not found');
    const articles = await res.json();
    const sorted = articles.slice().sort((a, b) => new Date(b.date) - new Date(a.date));

    if (sorted.length === 0) {
      container.innerHTML = `<p style="color:var(--text-light);text-align:center;grid-column:1/-1">${emptyMessage || 'No articles yet - check back soon!'}</p>`;
      return;
    }

    container.innerHTML = sorted.map(buildBlogCardHtml).join('');
  } catch (err) {
    console.error('Could not load articles:', err);
    container.innerHTML = `<p style="color:var(--text-light);text-align:center;grid-column:1/-1">Could not load articles right now.</p>`;
  }
}

function showToast(message) {
  const toast = document.createElement('div');
  toast.style.cssText = `position: fixed; bottom: 30px; left: 50%; transform: translateX(-50%); background: #1e293b; color: white; padding: 14px 28px; border-radius: 12px; font-weight: 600; font-size: 0.95rem; z-index: 9999; animation: slideUp 0.3s ease; box-shadow: 0 10px 30px rgba(0,0,0,0.3);`;
  toast.textContent = message;
  document.body.appendChild(toast);
  setTimeout(() => { toast.style.opacity = '0'; toast.style.transition = 'opacity 0.3s'; setTimeout(() => toast.remove(), 300); }, 2500);
}
