name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: https://petagecalc.in/
          destination-file: sitemap.xml
          include-extensions: html
          exclude: /about.html, /contact.html

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatically update sitemap.xml"
          file_pattern: sitemap.xml
